export const GEOPOSITION_PENDING = 'App/GEOPOSITION_PENDING';
export const GEOPOSITION_SUCCESS = 'App/GEOPOSITION_SUCCESS';
export const GEOPOSITION_ERROR = 'App/GEOPOSITION_ERROR';

export const BUS_PREDICTIONS_PENDING = 'App/BUS_PREDICTIONS_PENDING';
export const BUS_PREDICTIONS_SUCCESS = 'App/BUS_PREDICTIONS_SUCCESS';
export const BUS_PREDICTIONS_ERROR = 'App/BUS_PREDICTIONS_ERROR';
